/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package padron.listado;

/**
 *
 * @author fermani
 */
public class PnlListadoArticulos extends javax.swing.JPanel {

    /**
     * Creates new form PnlListadoArticulos
     */
    public PnlListadoArticulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hdrTituto = new org.jdesktop.swingx.JXHeader();

        setLayout(new java.awt.BorderLayout());

        hdrTituto.setDescription("Listado de árticulos");
        add(hdrTituto, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXHeader hdrTituto;
    // End of variables declaration//GEN-END:variables
}
